name: Check Links

on:
  push:
    paths:
      - '**/*'  # 监听所有文件的变化
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 运行链接检测脚本
      - name: Run link checker script
        run: python check.py

      # 5. 配置 Git 用户
      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 6. 添加生成的 JSON 文件到 Git
      - name: Commit and push changes if json file is updated
        run: |
          git add public/check_links.json
          git commit -m "Update check_links.json after link check" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
